### ISSUE TITLE
Shiny: Search func disables input$map_marker_click

### ISSUE THREAD

**Issue by NahuelGrasso** [bhaskarvk/leaflet.extras#46] opened 2016-12-28 20:17 UTC
Hi, I have a function that is activated every time I click on a marker, it works well until I use the search functionality. After that, it only works on the groups of markers not affected by the search.
does anyone have a clue what happened?
I have tested that the input$map_marker_click is not triggered for the group of markers (i.e. clubs) related to the search.

This is the way I configured the search:
map%>%addSearchMarker(
        targetGroup = 'clubs',
        options = searchMarkersOptions(propertyName = 'label',zoom=17, openPopup = FALSE))

To catch the event I use:
observe({
      click<-input$map_marker_click

Thanks in advance!
Nahuel

**Comment by bhaskarvk** [comment] 2016-12-29 15:03
I've no idea why that should happen, but I'll debug and hopefully fix it.

**Comment by bhaskarvk** [comment] 2017-07-22 14:00
Could you upload a minimal reproducible example on shinyapps.io?

**Comment by bhaskarvk** [comment] 2017-07-24 02:01
I think I lnow what the problem is. I will push a fix tomorrow.

**Comment by bhaskarvk** [comment] 2017-07-28 17:15
Fixed now!

**Closed by bhaskarvk** 2017-07-28 17:15 UTC
