### ISSUE TITLE
Deselect point after searching

### ISSUE THREAD

**Issue by LuukTX** [bhaskarvk/leaflet.extras#70] opened 2017-03-20 09:48 UTC
Hello,

I added a search marker to my leaflet map using your leaflet.extras-package. I used the following code:

%>% addSearchMarker(targetGroup = "stations",options = searchMarkersOptions(openPopup=T)

After I search for a data point, this data point is selected and highlighted. However, I can't deselect this data point after searching. Is there a way to deselect selected points after searching?

Thanks in advance!

**Comment by bhaskarvk** [comment] 2017-03-20 14:21
I will need to do some research on this. Stay tuned!

**Comment by bhaskarvk** [comment] 2017-07-19 17:05
Duplicate of #95. See solution posted in that issue.

**Closed by bhaskarvk** 2017-07-19 17:05 UTC
Labels: duplicate, question
